name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  check-xml:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - run: pip install pyxform==4.0.0
    - run: ./scripts/generate-form-xmls.sh
    - run: ./scripts/check-for-changes.sh
